name: Linting files on push

on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing node_modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
