name: Linting files on push

on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node_modules and run linter
        working-directory: ./bot
        run: |
          npm install
          npm run lint
          git config --global user.email "cartercostic@gmail.com"
          git config --global user.name "carterjc"
          git add .
          git commit -m "fixed ESLint issues"
          git push
