name: Linting files on push

on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install node_modules and run linter
        working-directory: ./bot
        run: |
          npm install
          npm run lint
          git config --global user.email "cartercostic@gmail.com"
          git config --global user.name "carterjc"
          git add .
          git diff-index --quiet HEAD || git commit -m "fixed ESLint issues"
          git push
